// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"learning-french-service/internal/ent/predicate"
	"learning-french-service/internal/ent/pronunciationattempt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PronunciationAttemptDelete is the builder for deleting a PronunciationAttempt entity.
type PronunciationAttemptDelete struct {
	config
	hooks    []Hook
	mutation *PronunciationAttemptMutation
}

// Where appends a list predicates to the PronunciationAttemptDelete builder.
func (_d *PronunciationAttemptDelete) Where(ps ...predicate.PronunciationAttempt) *PronunciationAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PronunciationAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PronunciationAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PronunciationAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pronunciationattempt.Table, sqlgraph.NewFieldSpec(pronunciationattempt.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PronunciationAttemptDeleteOne is the builder for deleting a single PronunciationAttempt entity.
type PronunciationAttemptDeleteOne struct {
	_d *PronunciationAttemptDelete
}

// Where appends a list predicates to the PronunciationAttemptDelete builder.
func (_d *PronunciationAttemptDeleteOne) Where(ps ...predicate.PronunciationAttempt) *PronunciationAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PronunciationAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pronunciationattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PronunciationAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
