// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"learning-french-service/internal/ent/predicate"
	"learning-french-service/internal/ent/pronunciationattempt"
	"learning-french-service/internal/ent/question"
	"learning-french-service/internal/ent/user"
	"learning-french-service/internal/ent/word"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PronunciationAttemptQuery is the builder for querying PronunciationAttempt entities.
type PronunciationAttemptQuery struct {
	config
	ctx          *QueryContext
	order        []pronunciationattempt.OrderOption
	inters       []Interceptor
	predicates   []predicate.PronunciationAttempt
	withUser     *UserQuery
	withQuestion *QuestionQuery
	withWord     *WordQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PronunciationAttemptQuery builder.
func (_q *PronunciationAttemptQuery) Where(ps ...predicate.PronunciationAttempt) *PronunciationAttemptQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PronunciationAttemptQuery) Limit(limit int) *PronunciationAttemptQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PronunciationAttemptQuery) Offset(offset int) *PronunciationAttemptQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PronunciationAttemptQuery) Unique(unique bool) *PronunciationAttemptQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PronunciationAttemptQuery) Order(o ...pronunciationattempt.OrderOption) *PronunciationAttemptQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *PronunciationAttemptQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pronunciationattempt.Table, pronunciationattempt.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pronunciationattempt.UserTable, pronunciationattempt.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuestion chains the current query on the "question" edge.
func (_q *PronunciationAttemptQuery) QueryQuestion() *QuestionQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pronunciationattempt.Table, pronunciationattempt.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pronunciationattempt.QuestionTable, pronunciationattempt.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWord chains the current query on the "word" edge.
func (_q *PronunciationAttemptQuery) QueryWord() *WordQuery {
	query := (&WordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pronunciationattempt.Table, pronunciationattempt.FieldID, selector),
			sqlgraph.To(word.Table, word.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pronunciationattempt.WordTable, pronunciationattempt.WordColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PronunciationAttempt entity from the query.
// Returns a *NotFoundError when no PronunciationAttempt was found.
func (_q *PronunciationAttemptQuery) First(ctx context.Context) (*PronunciationAttempt, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pronunciationattempt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) FirstX(ctx context.Context) *PronunciationAttempt {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PronunciationAttempt ID from the query.
// Returns a *NotFoundError when no PronunciationAttempt ID was found.
func (_q *PronunciationAttemptQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pronunciationattempt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PronunciationAttempt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PronunciationAttempt entity is found.
// Returns a *NotFoundError when no PronunciationAttempt entities are found.
func (_q *PronunciationAttemptQuery) Only(ctx context.Context) (*PronunciationAttempt, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pronunciationattempt.Label}
	default:
		return nil, &NotSingularError{pronunciationattempt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) OnlyX(ctx context.Context) *PronunciationAttempt {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PronunciationAttempt ID in the query.
// Returns a *NotSingularError when more than one PronunciationAttempt ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PronunciationAttemptQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pronunciationattempt.Label}
	default:
		err = &NotSingularError{pronunciationattempt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PronunciationAttempts.
func (_q *PronunciationAttemptQuery) All(ctx context.Context) ([]*PronunciationAttempt, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PronunciationAttempt, *PronunciationAttemptQuery]()
	return withInterceptors[[]*PronunciationAttempt](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) AllX(ctx context.Context) []*PronunciationAttempt {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PronunciationAttempt IDs.
func (_q *PronunciationAttemptQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pronunciationattempt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PronunciationAttemptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PronunciationAttemptQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PronunciationAttemptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PronunciationAttemptQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PronunciationAttemptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PronunciationAttemptQuery) Clone() *PronunciationAttemptQuery {
	if _q == nil {
		return nil
	}
	return &PronunciationAttemptQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]pronunciationattempt.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PronunciationAttempt{}, _q.predicates...),
		withUser:     _q.withUser.Clone(),
		withQuestion: _q.withQuestion.Clone(),
		withWord:     _q.withWord.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PronunciationAttemptQuery) WithUser(opts ...func(*UserQuery)) *PronunciationAttemptQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PronunciationAttemptQuery) WithQuestion(opts ...func(*QuestionQuery)) *PronunciationAttemptQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuestion = query
	return _q
}

// WithWord tells the query-builder to eager-load the nodes that are connected to
// the "word" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PronunciationAttemptQuery) WithWord(opts ...func(*WordQuery)) *PronunciationAttemptQuery {
	query := (&WordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWord = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserAudioURL string `json:"user_audio_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PronunciationAttempt.Query().
//		GroupBy(pronunciationattempt.FieldUserAudioURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PronunciationAttemptQuery) GroupBy(field string, fields ...string) *PronunciationAttemptGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PronunciationAttemptGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pronunciationattempt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserAudioURL string `json:"user_audio_url,omitempty"`
//	}
//
//	client.PronunciationAttempt.Query().
//		Select(pronunciationattempt.FieldUserAudioURL).
//		Scan(ctx, &v)
func (_q *PronunciationAttemptQuery) Select(fields ...string) *PronunciationAttemptSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PronunciationAttemptSelect{PronunciationAttemptQuery: _q}
	sbuild.label = pronunciationattempt.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PronunciationAttemptSelect configured with the given aggregations.
func (_q *PronunciationAttemptQuery) Aggregate(fns ...AggregateFunc) *PronunciationAttemptSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PronunciationAttemptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pronunciationattempt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PronunciationAttemptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PronunciationAttempt, error) {
	var (
		nodes       = []*PronunciationAttempt{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withQuestion != nil,
			_q.withWord != nil,
		}
	)
	if _q.withUser != nil || _q.withQuestion != nil || _q.withWord != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pronunciationattempt.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PronunciationAttempt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PronunciationAttempt{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *PronunciationAttempt, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withQuestion; query != nil {
		if err := _q.loadQuestion(ctx, query, nodes, nil,
			func(n *PronunciationAttempt, e *Question) { n.Edges.Question = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWord; query != nil {
		if err := _q.loadWord(ctx, query, nodes, nil,
			func(n *PronunciationAttempt, e *Word) { n.Edges.Word = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PronunciationAttemptQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PronunciationAttempt, init func(*PronunciationAttempt), assign func(*PronunciationAttempt, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PronunciationAttempt)
	for i := range nodes {
		if nodes[i].user_pronunciation_attempts == nil {
			continue
		}
		fk := *nodes[i].user_pronunciation_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_pronunciation_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PronunciationAttemptQuery) loadQuestion(ctx context.Context, query *QuestionQuery, nodes []*PronunciationAttempt, init func(*PronunciationAttempt), assign func(*PronunciationAttempt, *Question)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PronunciationAttempt)
	for i := range nodes {
		if nodes[i].question_pronunciation_attempts == nil {
			continue
		}
		fk := *nodes[i].question_pronunciation_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(question.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "question_pronunciation_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PronunciationAttemptQuery) loadWord(ctx context.Context, query *WordQuery, nodes []*PronunciationAttempt, init func(*PronunciationAttempt), assign func(*PronunciationAttempt, *Word)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PronunciationAttempt)
	for i := range nodes {
		if nodes[i].word_pronunciation_attempts == nil {
			continue
		}
		fk := *nodes[i].word_pronunciation_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(word.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "word_pronunciation_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PronunciationAttemptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PronunciationAttemptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pronunciationattempt.Table, pronunciationattempt.Columns, sqlgraph.NewFieldSpec(pronunciationattempt.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pronunciationattempt.FieldID)
		for i := range fields {
			if fields[i] != pronunciationattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PronunciationAttemptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pronunciationattempt.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pronunciationattempt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PronunciationAttemptGroupBy is the group-by builder for PronunciationAttempt entities.
type PronunciationAttemptGroupBy struct {
	selector
	build *PronunciationAttemptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PronunciationAttemptGroupBy) Aggregate(fns ...AggregateFunc) *PronunciationAttemptGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PronunciationAttemptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PronunciationAttemptQuery, *PronunciationAttemptGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PronunciationAttemptGroupBy) sqlScan(ctx context.Context, root *PronunciationAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PronunciationAttemptSelect is the builder for selecting fields of PronunciationAttempt entities.
type PronunciationAttemptSelect struct {
	*PronunciationAttemptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PronunciationAttemptSelect) Aggregate(fns ...AggregateFunc) *PronunciationAttemptSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PronunciationAttemptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PronunciationAttemptQuery, *PronunciationAttemptSelect](ctx, _s.PronunciationAttemptQuery, _s, _s.inters, v)
}

func (_s *PronunciationAttemptSelect) sqlScan(ctx context.Context, root *PronunciationAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
