// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"learning-french-service/internal/ent/predicate"
	"learning-french-service/internal/ent/questionreview"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionReviewDelete is the builder for deleting a QuestionReview entity.
type QuestionReviewDelete struct {
	config
	hooks    []Hook
	mutation *QuestionReviewMutation
}

// Where appends a list predicates to the QuestionReviewDelete builder.
func (_d *QuestionReviewDelete) Where(ps ...predicate.QuestionReview) *QuestionReviewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuestionReviewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuestionReviewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuestionReviewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(questionreview.Table, sqlgraph.NewFieldSpec(questionreview.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuestionReviewDeleteOne is the builder for deleting a single QuestionReview entity.
type QuestionReviewDeleteOne struct {
	_d *QuestionReviewDelete
}

// Where appends a list predicates to the QuestionReviewDelete builder.
func (_d *QuestionReviewDeleteOne) Where(ps ...predicate.QuestionReview) *QuestionReviewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuestionReviewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{questionreview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuestionReviewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
