// Code generated by ent, DO NOT EDIT.

package learningstreak

import (
	"learning-french-service/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLTE(FieldID, id))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldEndDate, v))
}

// StreakLength applies equality check predicate on the "streak_length" field. It's identical to StreakLengthEQ.
func StreakLength(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldStreakLength, v))
}

// IsCurrent applies equality check predicate on the "is_current" field. It's identical to IsCurrentEQ.
func IsCurrent(v bool) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldIsCurrent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldCreatedAt, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotNull(FieldEndDate))
}

// StreakLengthEQ applies the EQ predicate on the "streak_length" field.
func StreakLengthEQ(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldStreakLength, v))
}

// StreakLengthNEQ applies the NEQ predicate on the "streak_length" field.
func StreakLengthNEQ(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldStreakLength, v))
}

// StreakLengthIn applies the In predicate on the "streak_length" field.
func StreakLengthIn(vs ...int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIn(FieldStreakLength, vs...))
}

// StreakLengthNotIn applies the NotIn predicate on the "streak_length" field.
func StreakLengthNotIn(vs ...int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotIn(FieldStreakLength, vs...))
}

// StreakLengthGT applies the GT predicate on the "streak_length" field.
func StreakLengthGT(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGT(FieldStreakLength, v))
}

// StreakLengthGTE applies the GTE predicate on the "streak_length" field.
func StreakLengthGTE(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGTE(FieldStreakLength, v))
}

// StreakLengthLT applies the LT predicate on the "streak_length" field.
func StreakLengthLT(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLT(FieldStreakLength, v))
}

// StreakLengthLTE applies the LTE predicate on the "streak_length" field.
func StreakLengthLTE(v int) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLTE(FieldStreakLength, v))
}

// IsCurrentEQ applies the EQ predicate on the "is_current" field.
func IsCurrentEQ(v bool) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldIsCurrent, v))
}

// IsCurrentNEQ applies the NEQ predicate on the "is_current" field.
func IsCurrentNEQ(v bool) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldIsCurrent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LearningStreak {
	return predicate.LearningStreak(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LearningStreak {
	return predicate.LearningStreak(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LearningStreak {
	return predicate.LearningStreak(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LearningStreak) predicate.LearningStreak {
	return predicate.LearningStreak(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LearningStreak) predicate.LearningStreak {
	return predicate.LearningStreak(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LearningStreak) predicate.LearningStreak {
	return predicate.LearningStreak(sql.NotPredicates(p))
}
