server:
    port: 8080

mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    dbname: learning_french
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 3600

log:
    log_level: debug
    file_name: "logs/app1.log"
    max_size: 100 # MB
    max_backups: 3
    max_age: 30 # days
    compress: true

redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
